# Generated by Django 4.2.7 on 2023-12-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='ExhibitName',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
