# Generated by Django 4.2.7 on 2023-11-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ArtistName', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('DateBorn', models.IntegerField(default=None, null=True)),
                ('DateDied', models.IntegerField(default=None, null=True)),
                ('CountryOfOrigin', models.CharField(blank=True, max_length=20)),
                ('MainStyle', models.CharField(blank=True, max_length=20)),
                ('Epoch', models.CharField(blank=True, max_length=20)),
                ('ArtistDesc', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('ExhibitName', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtObject',
            fields=[
                ('IdNo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Title', models.CharField(default='Unknown', max_length=60)),
                ('YearMade', models.IntegerField(null=True)),
                ('Origin', models.CharField(blank=True, max_length=20)),
                ('Style', models.CharField(blank=True, max_length=20)),
                ('Epoch', models.CharField(blank=True, max_length=20)),
                ('ArtDesc', models.CharField(blank=True, max_length=20)),
                ('ArtistName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.artist')),
                ('ExhibitName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.exhibition')),
            ],
        ),
    ]
