# Generated by Django 4.2.7 on 2023-12-05 16:16

import django.core.validators
from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_exhibition_exhibitname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), mainapp.models.ValidateImageFile]),
        ),
    ]
