# Generated by Django 4.2.7 on 2023-11-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_painting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('CollName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('CollType', models.CharField(max_length=15)),
                ('Phone', models.CharField(max_length=15)),
                ('ContactPerson', models.CharField(blank=True, max_length=20)),
                ('Epoch', models.CharField(blank=True, max_length=20)),
                ('CollDesc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SculptureOrStatue',
            fields=[
                ('IdNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.artobject')),
                ('Material', models.CharField(max_length=50, null=True)),
                ('Height', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('Weight', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentCollection',
            fields=[
                ('IdNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.collection')),
                ('DateAquired', models.DateField()),
                ('PcollStatus', models.CharField(max_length=10)),
                ('Cost', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('IdNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.artobject')),
                ('DateBorrowed', models.DateField()),
                ('DateReturned', models.DateField()),
                ('CollName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.collection')),
            ],
        ),
    ]
