# Generated by Django 4.2.7 on 2023-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_collection_sculptureorstatue_permanentcollection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ArtistDesc',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
