# Generated by Django 4.2.7 on 2023-12-05 11:29

import django.core.validators
from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_artobject_imagenameconstraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artobject',
            name='ImageNameConstraint',
        ),
        migrations.AlterField(
            model_name='artobject',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), mainapp.models.validate_image_filename]),
        ),
    ]
