# Generated by Django 4.2.7 on 2023-11-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_artist_artistdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='ArtDesc',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
