# Generated by Django 4.2.7 on 2023-12-03 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_artobject_artistname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('IdNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.artobject')),
                ('ArtType', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
