# Generated by Django 4.2.7 on 2023-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_artist_dateborn_alter_artist_datedied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='DateBorn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='DateDied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
