# Generated by Django 4.2.7 on 2023-12-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_artist_dateborn_alter_artist_datedied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentcollection',
            name='IdNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.artobject'),
        ),
    ]
