# Generated by Django 4.2.7 on 2023-12-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_permanentcollection_idno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculptureorstatue',
            name='Height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sculptureorstatue',
            name='Material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sculptureorstatue',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
